version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: whyb-postgres-container
    environment:
      POSTGRES_PASSWORD: "${postgres_pass}"
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: my_db
        target: /var/lib/postgres
  adminer:
    image: adminer
    container_name: adminer_container
    restart: always
    ports:
      - 8080:8080
volumes:
  my_db:

# version: "3.8"
# services:
#   db:
#     image: postgres
#     container_name: my-project-db
#     restart: always
#     environment:
#       POSTGRES_PASSWORD: password
#       POSTGRES_USER: postgres
#       POSTGRES_DB: postgres
#     ports:
#       - "5432:5432"
#   adminer:
#     image: adminer
#     container_name: adminer-container
#     restart: always
#     ports:
#       - 8080:8080
# volumes:
#   my_db_files:
  
